var listings = {
    footwear: {
      listing1: {
        name: "Supreme x Yeezy Boost 350 Black",
        askPrice: "100",
        avgSold: "125",
        imgSrc: "images/footwear/footwear_1_yb.jpg",
        imgAlt: "Yeezy Boost 350",
        description: "",
        dateCreated: "",
      },
      listing2: {
        name: "Air Force 1 High Supreme",
        askPrice: "1000",
        avgSold: "1250",
        imgSrc: "images/footwear/footwear_2_afo.jpg",
        imgAlt: "AF1",
        description: "",
        dateCreated: "",
      },
      listing3: {
        name: "Supreme x Nike SB Dunk Low Black Cement",
        askPrice: "1000",
        avgSold: "1250",
        imgSrc: "images/footwear/footwear_3_sbd.jpg",
        imgAlt: "SB Dunk",
        description: "",
        dateCreated: "",
      },
      listing4: {
        name: "Nike Air Foamposite One Supreme SP",
        askPrice: "1000",
        avgSold: "1250",
        imgSrc: "images/footwear/footwear_4_fpo.jpg",
        imgAlt: "Foamposite One",
        description: "",
        dateCreated: "",
      },
      listing5: {
        name: "Supreme x Nike Air More Uptempo",
        askPrice: "1000",
        avgSold: "1250",
        imgSrc: "images/footwear/footwear_5_amu.jpeg",
        imgAlt: "Air More Uptempo",
        description: "",
        dateCreated: "",
      },
      listing6: {
        name: "Supreme x Louis Vuitton Run Sneaker",
        askPrice: "1250",
        avgSold: "1500",
        imgSrc: "images/footwear/footwear_6_lv.jpeg",
        imgAlt: "LV Sneakers",
        description: "",
        dateCreated: "",
      }
    },
    apparel: {
      listing1: {
        name: "Supreeme Ladybug Tee",
        askPrice: "40",
        avgSold: "50",
        imgSrc: "images/apparel/apparel_1_ladybug.jpg",
        imgAlt: "Ladybug Tee",
        description: "",
        dateCreated: "",
      },
      listing2: {
        name: "Supreme Sekintani LA Norihiro Tee",
        askPrice: "40",
        avgSold: "50",
        imgSrc: "images/apparel/apparel_2_norihiro.jpg",
        imgAlt: "Sekintani Norihiro",
        description: "",
        dateCreated: "",
      },
      listing3: {
        name: "Supreme Cat Hoodie",
        askPrice: "400",
        avgSold: "420",
        imgSrc: "images/apparel/apparel_3_cat.jpg",
        imgAlt: "Cat Hoodie",
        description: "",
        dateCreated: "",
      },
      listing4: {
        name: "Supreme Classic Ad Hoodie",
        askPrice: "60",
        avgSold: "80",
        imgSrc: "images/apparel/apparel_4_classic_ad.jpg",
        imgAlt: "Classic Ad Hoodie",
        description: "",
        dateCreated: "",
      },
      listing5: {
        name: "Supreme Motion Logo Varsity Jacket",
        askPrice: "150",
        avgSold: "200",
        imgSrc: "images/apparel/apparel_5_motion_logo.jpg",
        imgAlt: "Motion Logo Jacket",
        description: "",
        dateCreated: "",
      },
      listing6: {
        name: "Supreme North Face Mountain Parka",
        askPrice: "200",
        avgSold: "300",
        imgSrc: "images/apparel/apparel_6_northface.jpg",
        imgAlt: "North Face Parka",
        description: "",
        dateCreated: "",
      }
    },
    accessories: {
      listing1: {
        name: "Supreme Thermos",
        askPrice: "100",
        avgSold: "125",
        imgSrc: "images/accessories/accessories_1_thermos.jpg",
        imgAlt: "Thermos",
        description: "",
        dateCreated: "",
      },
      listing2: {
        name: "Supreme North Face Expedition Backpack",
        askPrice: "500",
        avgSold: "750",
        imgSrc: "images/accessories/accessories_2_backpack.jpg",
        imgAlt: "North Face Backpack",
        description: "",
        dateCreated: "",
      },
      listing3: {
        name: "Supreme Shoulder Bag",
        askPrice: "150",
        avgSold: "200",
        imgSrc: "images/accessories/accessories_3_shoulder_bag.jpg",
        imgAlt: "Shoulder Bag",
        description: "",
        dateCreated: "",
      },
      listing4: {
        name: "Supreme FW18 Backpack",
        askPrice: "300",
        avgSold: "350",
        imgSrc: "images/accessories/accessories_4_backpack.jpg",
        imgAlt: "FW18 Backpack",
        description: "",
        dateCreated: "",
      },
      listing5: {
        name: "Supreme Jean-Paul Gaultier Cologne",
        askPrice: "200",
        avgSold: "250",
        imgSrc: "images/accessories/accessories_5_cologne.jpg",
        imgAlt: "Jean-Paul Gaultier Cologne",
        description: "",
        dateCreated: "",
      },
      listing6: {
        name: "Supreme ShedRain Umbrella Red",
        askPrice: "250",
        avgSold: "300",
        imgSrc: "images/accessories/accessories_6_umberlla.jpg",
        imgAlt: "ShedRain Umbrella",
        description: "",
        dateCreated: "",
      }
    },
    collectibles: {
      listing1: {
        name: "Supreme Boxing Gloves",
        askPrice: "100",
        avgSold: "150",
        imgSrc: "images/collectibles/collectibles_1_boxing.jpg",
        imgAlt: "Boxing Gloves",
        description: "",
        dateCreated: "",
      },
      listing2: {
        name: "Supreme Nunchucks",
        askPrice: "500",
        avgSold: "600",
        imgSrc: "images/collectibles/collectibles_2_nunchucks.jpg",
        imgAlt: "Nunchucks",
        description: "",
        dateCreated: "",
      },
      listing3: {
        name: "Supreme Basketball",
        askPrice: "200",
        avgSold: "225",
        imgSrc: "images/collectibles/collectibles_3_basketball.jpg",
        imgAlt: "Basketball",
        description: "",
        dateCreated: "",
      },
      listing4: {
        name: "Supreme Baseball",
        askPrice: "300",
        avgSold: "350",
        imgSrc: "images/collectibles/collectibles_4_baseball.jpg",
        imgAlt: "Baseball",
        description: "",
        dateCreated: "",
      },
      listing5: {
        name: "Supreme Skate Tool",
        askPrice: "50",
        avgSold: "75",
        imgSrc: "images/collectibles/collectibles_5_skate_tool.jpg",
        imgAlt: "Skate Tool",
        description: "",
        dateCreated: "",
      },
      listing6: {
        name: "Supreme Bolt Cutters",
        askPrice: "300",
        avgSold: "350",
        imgSrc: "images/collectibles/collectibles_6_bolt_cutters.jpg",
        imgAlt: "Bolt Cutters",
        description: "",
        dateCreated: "",
      }
    }
};
   



// Stop at 10 listings
// Page 2 generates listings 11 - 20; Page 3 generates listings 21-30, and so on.

// Clicking into each listing will generate page using object properties